### ISSUE TITLE
Problems after 1.8.1. Patch

### ISSUE THREAD

**Issue by MAXQON** [pchoiniere/FS22ModManager#1]
After Patching the Servers to 1.8.1 the Manager shows up the error : Unable to detect the Farming Simulator dedicated Server version.  with auto Update and auto delete enabled it delete´s all Mods in that case.
Maybe you have an idea whats happend with that Patch  greets from Germany and thanks for you´re nice work

**Comment by pchoiniere** [comment]
Likely the dedicated server IP address was changed by the hosting provider. This has happened to me and just getting the new url/ip fixes this.

**Comment by pchoiniere** [comment]
Look's like Giants changed the dedicated server mod list page format.

**Comment by pchoiniere** [comment]
Fix in version 1.1.4
