### ISSUE TITLE
Project laid down?

### ISSUE THREAD

**Issue by djdanby** [pchoiniere/FS22ModManager#2]
Good day. 
Have you put down your project? Or why have all the files disappeared here?
There are currently problems with your mod manager due to an update from Giants.

The following message appears:
**"Unable to detect the farming siumlator dedicated server version".**

We were actually hoping for an update. However, I no longer see any download files here :(

Edit: 
Ok. Mod Manager found. It's in the Docs folder. You should tidy things up here. :D 
You have 2 times Mod Manager in it. One is FS22ModManager, which is out of date according to the version number. And FSModManager, which is obviously the current one, but is in the Docs folder instead of the Release area.

So this error message applies to the latest version of your mod manager (1.2.4.105). Giants has patched the server version to 1.12, which means that the servers are no longer recognised.

**Comment by pchoiniere** [comment]
This url was retired. The new URL is below. Giant's patch change the version number of the mod page.  Working on a fix now, should have a new version today.
 https://github.com/pchoiniere/FSModManager
 Download link:  https://github.com/pchoiniere/FSModManager/blob/main/docs/download/FSModManagerSetup.exe

**Comment by pchoiniere** [comment]
New version is uploaded
